[package]
authors = ["elois <elois@duniter.org>"]
description = "Set of libraries implementing the DUBP protocol."
edition = "2018"
keywords = ["duniter", "dubp"]
license = "AGPL-3.0"
name = "dubp"
readme = "README.md"
repository = "https://git.duniter.org/libs-dupb-rs-libs"
version = "0.41.1"

[lib]
path = "lib.rs"

[dependencies]
dup-crypto = { path = "crypto", version = "0.41.1", features = ["scrypt"] }
dubp-common = { path = "common", version = "0.41.1", features = ["crypto_scrypt"] }
dubp-wallet = { path = "wallet", version = "0.41.1", features = ["crypto_scrypt"] }
dubp-documents = { path = "documents", version = "0.41.1", features = ["crypto_scrypt"] }
dubp-documents-parser = { path = "documents-parser", version = "0.41.1", features = ["crypto_scrypt"] }
dubp-block = { path = "block", version = "0.41.1", features = ["crypto_scrypt"] }

[dev-dependencies]
rusty-hook = "0.11.2"

[workspace]
members = [
    "block",
    "common",
    "crypto",
    "documents",
    "documents-parser",
    "wallet"
]

[profile.test]
opt-level = 3

[patch.crates-io]
#json-pest-parser = { path = "../../../rust/json-pest-parser" }
