[workspace]
members = [
    "common",
    "crypto",
    "currency-params",
    "documents",
    "documents-parser"
]

[patch.crates-io]
#json-pest-parser = { path = "../../../rust/json-pest-parser" }
