[workspace]
members = [
    "block",
    "common",
    "crypto",
    "documents",
    "documents-parser",
    "wallet"
]

[patch.crates-io]
#json-pest-parser = { path = "../../../rust/json-pest-parser" }
